# Generated by Django 5.0.6 on 2024-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_categories'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.ManyToManyField(to='categories.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_assign_date',
            field=models.DateTimeField(),
        ),
    ]
